export enum IPCEvents {
  GET_LOCAL_IP = 'GET_LOCAL_IP',
  GET_LOCAL_IP_SUCCESS = 'GET_LOCAL_IP_SUCCESS',

  START_SYNC_SERVER = 'START_SYNC_SERVER',
  STOP_SYNC_SERVER = 'STOP_SYNC_SERVER',

  SYNC_HANDSHAKE = 'SYNC_HANDSHAKE',
  SYNC_HANDSHAKE_RESULT = 'SYNC_HANDSHAKE_RESULT',
}
